// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rodrigo.meioambiente.domain;

import com.rodrigo.meioambiente.domain.Meioambiente;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Meioambiente_Roo_Configurable {
    
    declare @type: Meioambiente: @Configurable;
    
}
